#include "Localization.hpp"

#include <algorithm>
#include <array>

namespace Localization {
namespace {

struct Entry {
    const char* key;
    const char* value;
};

constexpr std::array<Entry, 304> kSimplifiedChinese{{
    {"Transparency", "UI透明"},
    {"vrzwk", "汉化：vrzwk汉化组(vrzwk.com)"},
    {"Makes the UI transparent when not focused.", "UI界面无焦点时透明。"},
    {"Input Passthrough", "输入直通"},
    {"Allows mouse and keyboard inputs to register to the game while the UI is focused.", "当UI界面获取焦点时，允许鼠标和键盘输入到游戏。"},
    {"Show Advanced Options", "显示高级选项"},
    {"Show additional options for greater control over various settings.", "显示其他选项以更好地进行各种设置。"},
    {"Reset to Default Settings", "恢复默认设置"},
    {"Keyboard Menu Key: Insert", "键盘菜单键：插入"},
    {"Gamepad L3 + R3: Toggle Menu", "手柄 L3+R3：切换菜单"},
    {"Gamepad RT: Shortcuts", "手柄 RT：快捷键"},
    {"Gamepad LB/RB: Change Sidebar Page", "手柄 LB/RB：更改边栏页面"},
    {"About", "关于"},
    {"Not bound", "未绑定"},
    {"Press any key...", "按下任意键..."},
    {"FrameworkConfig", "框架配置"},
    {"Main", "主页"},
    {"GUI/Themes", "视图/主题"},
    {"Menu Key", "菜单键"},
    {"Show Cursor Key", "显示光标键"},
    {"Remember Menu Open/Closed State", "记住菜单打开/关闭状态"},
    {"Enable L3 + R3 Toggle", "启用 L3 + R3 切换"},
    {"Always Show Cursor", "光标一直显示"},
    {"Select GUI Theme", "选择界面主题"},
    {"Font Size", "字体大小"},
    {"Attempt Unload Plugins", "尝试卸载插件"},
    {"Reload Plugins", "重新加载插件"},
    {"Loaded plugins:", "已加载插件:"},
    {"No plugins loaded.", "未加载任何插件。"},
    {"Errors:", "错误:"},
    {"Warnings:", "警告:"},
    {"Author: praydog", "作者：praydog"},
    {"Licenses", "开源许可"},
    {"Runtime", "运行时"},
    {"Unreal", "虚幻引擎"},
    {"Input", "输入"},
    {"Camera", "相机"},
    {"Keybinds", "按键绑定"},
    {"WARNING: Hardware-accelerated GPU scheduling is enabled. This may cause the game to run slower.", "警告：启用了硬件加速GPU调度。这可能会导致游戏运行速度变慢。"},
    {"Go into your Windows Graphics settings and disable \"Hardware-accelerated GPU scheduling\"", "进入您的Windows图形设置并禁用“硬件加速GPU调度”"},
    {"Note: This is only necessary if you are experiencing performance issues.", "注意：只有在遇到性能问题时才需要执行此操作。"},
    {"Unknown page selected", "选择了未知页面"},
    {"Runtime Information (", "运行时信息 ("},
    {"Desktop Spectator View", "桌面观众视图"},
    {"2D Screen Mode", "2D屏幕模式"},
    {"Render Resolution (per-eye): %d x %d", "渲染分辨率（单眼）: %d x %d"},
    {"Total Render Resolution: %d x %d", "总渲染分辨率: %d x %d"},
    {"Overlay Options", "覆盖选项"},
    {"Overlay Type", "覆盖类型"},
    {"UI Cylinder Angle", "UI柱面角度"},
    {"UI Offset", "UI偏移"},
    {"UI Distance", "UI距离"},
    {"UI Size", "UI大小"},
    {"UI Follows View", "UI跟随视图"},
    {"Framework Distance", "框架距离"},
    {"Framework Size", "框架大小"},
    {"Framework Follows View", "框架跟随视图"},
    {"Framework Wrist UI", "框架手腕UI"},
    {"Framework Mouse Emulation", "框架鼠标模拟"},
    {"Resolution can be changed in SteamVR", "可在SteamVR中更改分辨率"},
    {"Rendering Method", "渲染模式"},
    {"Synced Sequential Method", "同步顺序模式"},
    {"World Scale", "世界比例"},
    {"Depth Scale", "深度比例"},
    {"Disable HZBOcclusion", "禁用HZBOctication"},
    {"Disable Instance Culling", "禁用实例裁减"},
    {"Disable HDR Composition", "禁用HDR合成"},
    {"Disable Blur Widgets", "禁用模糊工具"},
    {"Continue holding down L3 + R3 to toggle aim method", "继续按住 L3+R3 切换瞄准方法"},
    {"AimMethod Notification", "瞄准方法通知"},
    {"RT Modifier Controls", "RT 修改器控件"},
    {"RT + Left Stick: Camera left/right/forward/back", "RT + 左摇杆：相机 左/右/前进/后退"},
    {"RT + Right Stick: Camera up/down", "RT + 右摇杆：相机 上/下"},
    {"Page: %d", "页: %d"},
    {"DPad Left: Previous page | DPad Right: Next page", "左DPad：上一页 | 右DPad：下一页"},
    {"RT + B: Save Camera 2", "RT + B：保存相机2"},
    {"RT + Y: Save Camera 1", "RT + Y：保存相机1"},
    {"RT + X: Save Camera 0", "RT + X：保存相机0"},
    {"RT + B: Load Camera 2", "RT + B：加载相机2"},
    {"RT + Y: Load Camera 1", "RT + Y：加载相机1"},
    {"RT + X: Load Camera 0", "RT + X：加载相机0"},
    {"RT + B: Reset camera offset", "RT + B：重置相机偏移"},
    {"RT + Y: Recenter view", "RT + Y：重置中心视图"},
    {"RT + X: Reset standing origin", "RT + X：重置站立原点"},
    {"Uncap Framerate", "取消帧率上限"},
    {"Enable GUI", "开启视图"},
    {"Enable Depth", "开启深度"},
    {"Load Blueprint Code", "加载蓝图代码"},
    {"Ghosting Fix", "修复鬼影"},
    {"Near Clip Plane", "近裁剪面"},
    {"Enable", "开启"},
    {"Value", "值"},
    {"Controller", "控制器"},
    {"VR Joystick Deadzone", "VR 摇杆死区"},
    {"DPad Shifting", "DPad 移位"},
    {"DPad Shifting Method", "DPad 移位方法"},
    {"Aim Method", "瞄准方法"},
    {"Experimental, may crash", "实验性的，可能会崩溃"},
    {"Some games may not work with this enabled.", "启用此功能后，某些游戏可能无法运行。"},
    {"Type", "类型"},
    {"Speed", "速度"},
    {"Smoothing", "平滑"},
    {"Modify Player Control Rotation", "修改玩家转向控制"},
    {"Use Pawn Control Rotation", "使用Pawn控制旋转"},
    {"Multiplayer Support", "多人游戏支持"},
    {"Snap Turn", "急转"},
    {"Enabled", "已启用"},
    {"Set Snap Turn Rotation Angle in Degrees.", "以度为单位设置捕捉旋转旋转角度。"},
    {"Angle", "角度"},
    {"Set Snap Turn Joystick Deadzone.", "设置快速转动摇杆死区。"},
    {"Deadzone", "死区"},
    {"Movement Orientation", "运动方向"},
    {"Roomscale Movement", "室内运动"},
    {"Save Camera 0", "保存相机0"},
    {"Save Camera 1", "保存相机1"},
    {"Save Camera 2", "保存相机2"},
    {"Load Camera 0", "加载相机0"},
    {"Load Camera 1", "加载相机1"},
    {"Load Camera 2", "加载相机2"},
    {"Decoupled Pitch", "场地解耦"},
    {"Auto Adjust UI", "自动调整UI"},
    {"Playspace Keys", "游戏空间按键"},
    {"Recenter View Key", "重新居中视图键"},
    {"Set Standing Origin Key", "重置视图键"},
    {"Camera Keys", "相机按键"},
    {"Load Camera 0 Key", "加载相机0按键"},
    {"Load Camera 1 Key", "加载相机1按键"},
    {"Load Camera 2 Key", "加载相机2按键"},
    {"Overlay/Runtime Keys", "叠加/运行时按键"},
    {"Toggle 2D Screen Mode Key", "切换2D屏幕模式键"},
    {"Disable VR Key", "禁用VR键"},
    {"Compatibility Options", "兼容性选项"},
    {"Skip UObjectArray Init", "跳过UObjectArray初始化"},
    {"Skip PostInitProperties", "跳过PostInitProperties"},
    {"SceneView Compatibility Mode", "场景视图兼容模式"},
    {"Extreme Compatibility Mode", "极端兼容模式"},
    {"Splitscreen Compatibility", "分屏兼容性"},
    {"Index", "序号"},
    {"Sync Mode", "同步模式"},
    {"Early\0Late\0Very Late\0", "早\0晚\0非常晚\0"},
    {"Right Bounds", "右侧边界"},
    {"Left Bounds", "左侧边界"},
    {"Disable Projection Matrix Override", "禁用投影矩阵覆盖"},
    {"Disable View Matrix Override", "禁用视图矩阵覆盖"},
    {"Disable Backbuffer Size Override", "禁用备份缓冲区大小覆盖"},
    {"Disable VR Overlay", "禁用VR覆盖"},
    {"Disable VR Entirely", "完全禁用VR"},
    {"Stereo Emulation Mode", "立体声仿真模式"},
    {"Wait for Present", "等待呈现"},
    {"Controllers allowed", "允许的控制器"},
    {"Controller test mode", "控制器测试模式"},
    {"Prediction Scale", "预测标尺"},
    {"Raw Left", "左"},
    {"Raw Right", "右"},
    {"Left Stick", "左摇杆"},
    {"Right Stick", "右摇杆"},
    {"Hardware scheduling: %s", "硬件调度: %s"},
    {"Disabled", "已禁用"},
    {"Loading...", "加载中..."},
    {"%s not loaded: %s not found", "%s未被加载: 未找到%s"},
    {"Please select %s from the loader if you want to use %s", "请从加载器中选择%s，如果你想使用%s的话"},
    {"%s not loaded: %s", "%s未被加载: %s"},
    {"%s not loaded: Unknown error", "%s未被加载: 未知错误"},
    {"No runtime loaded.", "未加载任何运行时。"},
    {"Attempt to reinitialize", "尝试重新初始化"},
    {"Set Standing Height", "设置站立高度"},
    {"Set Standing Origin", "设置站立原点"},
    {"Recenter View", "重新居中视图"},
    {"Reinitialize Runtime", "重新初始化运行时"},
    {"Console/CVars", "控制台/CVars"},
    {"Compatibility", "兼容性"},
    {"Debug", "调试"},
    {"Note: Any changes here will be frozen.", "注意：此处的任何更改都将被冻结。"},
    {"Frozen CVars: %i", "冻结的CVars: %i"},
    {"Display Console", "显示控制台"},
    {"Spawn Native Console", "生成本地控制台"},
    {"Dump All CVars", "转储所有CVars"},
    {"Clear Frozen CVars", "清除冻结的CVars"},
    {"Failed to get FConsoleManager.", "无法获取FConsoleManager。"},
    {"Note: This is a homebrew console. It is not the same as the in-game console.", "注意: 这是一个自制的控制台，与游戏中的控制台不同。"},
    {"Command", "命令"},
    {"Description", "描述"},
    {"Failed to find cvar: %s", "未能找到cvar：%s"},
    {"Unimplemented cvar type: %s", "未实现的cvar类型：%s"},
    {"Failed to read cvar: %s", "读取cvar失败: %s"},
    {"Failed to find cvar data: %s", "查找cvar数据失败: %s"},
    {"Failed to read cvar data: %s", "读取cvar数据失败: %s"},
    {"Stereo Hook Options", "立体钩子选项"},
    {"Asynchronous Code Scanning", "异步代码扫描"},
    {"Recreate Textures on Reset", "重置时重新创建纹理"},
    {"Frame Delay Compensation", "帧延迟补偿"},
    {"Config", "配置"},
    {"Developer", "开发者"},
    {"PluginLoader", "插件加载器"},
    {"Waiting for UObjectBase to be hooked...", "等待UObjectBase被挂钩..."},
    {"Reload Persistent States", "重新加载持久状态"},
    {"Destroy Persistent States", "清除持久状态"},
    {"Enabled at Startup", "在启动时启用"},
    {"Enable Attach Lerp", "启用附加Lerp"},
    {"Dump SDK", "转储SDK"},
    {"Attached Components", "附加组件"},
    {"Detach all", "全部分离"},
    {"Attached Camera Object", "附加相机对象"},
    {"Detach Camera", "分离相机"},
    {"Spawn Overlapper", "生成叠加器"},
    {"Overlapped Objects", "叠加的对象"},
    {"Destroy Overlapper", "清除叠加器"},
    {"Attach all", "附加全部"},
    {"Objects: %zu (%zu actual)", "对象: %zu (真实 %zu)"},
    {"Recent Objects", "最近使用的对象"},
    {"Common Objects", "公共对象"},
    {"PlayerController", "玩家控制器"},
    {"Player Controller", "玩家控制器"},
    {"No player controller", "无玩家控制器"},
    {"Acknowledged Pawn", "已确认生成"},
    {"No pawn", "未生成"},
    {"Camera Manager", "相机管理器"},
    {"No camera manager", "无相机管理器"},
    {"World", "世界"},
    {"No world", "无世界"},
    {"Objects by class", "按类排列对象"},
    {"Filter", "过滤"},
    {"Add Component Permanently", "永久添加组件"},
    {"Copy Name", "复制名称"},
    {"Copy Address", "复制地址"},
    {"Set to Screen Space", "设置为屏幕空间"},
    {"Detach", "分离"},
    {"Adjust", "调整"},
    {"Permanent Change", "永久变更"},
    {"Save state", "保存状态"},
    {"Can't save, did not start from a valid base or none of the allowed bases can reach this component", "无法保存，没有从有效的基类开始的，或者允许的基类不能达到此组件"},
    {"Attach left", "附加左侧"},
    {"Attach right", "附加右侧"},
    {"Attach Camera to", "附加相机到"},
    {"Attach Camera to (Relative)", "附加相机到(相对的)"},
    {"Camera Offset", "相机偏移"},
    {"Visible", "显示"},
    {"Save Visibility State", "保存隐藏显示状态"},
    {"Apply to all actors", "适用于所有参与者"},
    {"Add Component", "添加组件"},
    {"Components", "组件"},
    {"Call", "调用"},
    {"Disable", "关闭"},
    {"Can't save, did not start from a valid base", "无法保存，没有从有效的基类开始"},
    {"Empty array", "空数组"},
    {"Failed to get inner property", "无法获取内部属性"},
    {"Failed to get inner property class", "无法获取内部属性类"},
    {"Array of %s (unsupported)", "%s数组(不支持)"},
    {"Inheritance", "继承"},
    {"Functions", "方法"},
    {"Properties", "属性"},
    {"UObjectHook is disabled", "UObjectHook已禁用"},
    {"Re-enable", "重新启用"},
    {"RotationOffset", "旋转偏移"},
    {"PositionOffset", "位置偏移"},
    {"L3 + R3 Long Press Menu Toggle", "L3 + R3 长按菜单切换"},
    {"Debug Stats", "调试信息"},
    {"Select GUI Language", "选择界面语言"},
    {"Runtime Information (NONE)", "运行时信息 (无)"},
    {"Log Level", "日志等级"},
    {"Enable Depth-based Latency Reduction", "启用基于深度降低延迟"},
    {"Controller Pitch Offset", "控制器间距偏移"},
    {"Left-handed Controller Inputs", "左控制器输入"},
    {"Freeze Position", "冻结位置"},
    {"Freeze Rotation", "冻结旋转"},
    {"Recenter Horizon Key", "重置地面中心快捷键"},
    {"Toggle In-Game UI Key", "切换游戏界面快捷键"},
    {"AHUD UI Compatibility", "AHUD UI兼容性"},
    {"Vertical Projection", "垂直投影"},
    {"Horizontal Projection", "水平投影"},
    {"Scale Render Target", "缩放渲染目标"},
    {"Show FPS", "显示帧率"},
    {"Show Engine Statistics", "显示引擎统计信息"},
    {"Attach Lerp Speed", "附加Lerp速度"},
    {"UObjectHook Keybinds", "UObjectHook按键绑定"},
    {"Disable UObjectHook Key", "禁用UObjectHook快捷键"},
    {"Constructor calls: %llu", "构造函数调用: %llu"},
    {"Destructor calls: %llu", "析构函数调用: %llu"},
    {"Native Stereo", "原生立体"},
    {"Synchronized Sequential", "同步序列"},
    {"Alternating/AFR", "交替帧渲染/AFR"},
    {"Skip Tick", "跳过下一刻"},
    {"Skip Draw", "跳过绘制"},
    {"Game", "游戏"},
    {"Head/HMD", "头部/头显"},
    {"Right Controller", "右控制器"},
    {"Left Controller", "左控制器"},
    {"Two Handed (Right)", "双手 (右)"},
    {"Two Handed (Left)", "双手 (左)"},
    {"Left Joystick (Disables Standard Joystick Input)", "Left Joystick (禁用标准摇杆输入)"},
    {"Right Joystick (Disables Standard Joystick Input)", "Right Joystick (禁用标准摇杆输入)"},
    {"Gesture (Head) + Left Joystick", "手势 (头部) + 左摇杆"},
    {"Gesture (Head) + Right Joystick", "手势 (头部) + 右摇杆"},
    {"Raw / default", "原始 / 默认"},
    {"Symmetrical", "对称"},
    {"Mirrored", "镜像"},
    {"Matched", "匹配"},
    {"Default Dark", "默认暗色"},
    {"Alternative Dark", "另类暗色"},
    {"Default Light", "默认明亮"},
    {"High Contrast", "高对比度"},
    {"Early", "早"},
    {"Late", "晚"},
    {"Very Late", "非常晚"},
}};

constexpr std::array<Entry, 304> kTraditionalChinese{{
    {"Transparency", "UI透明"},
    {"vrzwk", "漢化：vrzwk漢化組(vrzwk.com)"},
    {"Makes the UI transparent when not focused.", "UI界面無焦點時透明。"},
    {"Input Passthrough", "輸入直通"},
    {"Allows mouse and keyboard inputs to register to the game while the UI is focused.", "當UI界面獲取焦點時，允許鼠標和鍵盤輸入到遊戲。"},
    {"Show Advanced Options", "顯示高級選項"},
    {"Show additional options for greater control over various settings.", "顯示其他選項以更好地進行各種設置。"},
    {"Reset to Default Settings", "恢複默認設置"},
    {"Keyboard Menu Key: Insert", "鍵盤菜單鍵：插入"},
    {"Gamepad L3 + R3: Toggle Menu", "手柄 L3+R3：切換菜單"},
    {"Gamepad RT: Shortcuts", "手柄 RT：快捷鍵"},
    {"Gamepad LB/RB: Change Sidebar Page", "手柄 LB/RB：更改邊欄頁面"},
    {"About", "關于"},
    {"Not bound", "未綁定"},
    {"Press any key...", "按下任意鍵..."},
    {"FrameworkConfig", "框架配置"},
    {"Main", "主頁"},
    {"GUI/Themes", "視圖/主題"},
    {"Menu Key", "菜單鍵"},
    {"Show Cursor Key", "顯示光標鍵"},
    {"Remember Menu Open/Closed State", "記住菜單打開/關閉狀態"},
    {"Enable L3 + R3 Toggle", "啓用 L3 + R3 切換"},
    {"Always Show Cursor", "光標壹直顯示"},
    {"Select GUI Theme", "選擇界面主題"},
    {"Font Size", "字體大小"},
    {"Attempt Unload Plugins", "嘗試卸載插件"},
    {"Reload Plugins", "重新加載插件"},
    {"Loaded plugins:", "已加載插件:"},
    {"No plugins loaded.", "未加載任何插件。"},
    {"Errors:", "錯誤:"},
    {"Warnings:", "警告:"},
    {"Author: praydog", "作者：praydog"},
    {"Licenses", "開源許可"},
    {"Runtime", "運行時"},
    {"Unreal", "虛幻引擎"},
    {"Input", "輸入"},
    {"Camera", "相機"},
    {"Keybinds", "按鍵綁定"},
    {"WARNING: Hardware-accelerated GPU scheduling is enabled. This may cause the game to run slower.", "警告：啓用了硬件加速GPU調度。這可能會導致遊戲運行速度變慢。"},
    {"Go into your Windows Graphics settings and disable \"Hardware-accelerated GPU scheduling\"", "進入您的Windows圖形設置並禁用“硬件加速GPU調度”"},
    {"Note: This is only necessary if you are experiencing performance issues.", "注意：只有在遇到性能問題時才需要執行此操作。"},
    {"Unknown page selected", "選擇了未知頁面"},
    {"Runtime Information (", "運行時信息 ("},
    {"Desktop Spectator View", "桌面觀衆視圖"},
    {"2D Screen Mode", "2D屏幕模式"},
    {"Render Resolution (per-eye): %d x %d", "渲染分辨率（單眼）: %d x %d"},
    {"Total Render Resolution: %d x %d", "總渲染分辨率: %d x %d"},
    {"Overlay Options", "覆蓋選項"},
    {"Overlay Type", "覆蓋類型"},
    {"UI Cylinder Angle", "UI柱面角度"},
    {"UI Offset", "UI偏移"},
    {"UI Distance", "UI距離"},
    {"UI Size", "UI大小"},
    {"UI Follows View", "UI跟隨視圖"},
    {"Framework Distance", "框架距離"},
    {"Framework Size", "框架大小"},
    {"Framework Follows View", "框架跟隨視圖"},
    {"Framework Wrist UI", "框架手腕UI"},
    {"Framework Mouse Emulation", "框架鼠標模擬"},
    {"Resolution can be changed in SteamVR", "可在SteamVR中更改分辨率"},
    {"Rendering Method", "渲染模式"},
    {"Synced Sequential Method", "同步順序模式"},
    {"World Scale", "世界比例"},
    {"Depth Scale", "深度比例"},
    {"Disable HZBOcclusion", "禁用HZBOctication"},
    {"Disable Instance Culling", "禁用實例裁減"},
    {"Disable HDR Composition", "禁用HDR合成"},
    {"Disable Blur Widgets", "禁用模糊工具"},
    {"Continue holding down L3 + R3 to toggle aim method", "繼續按住 L3+R3 切換瞄准方法"},
    {"AimMethod Notification", "瞄准方法通知"},
    {"RT Modifier Controls", "RT 修改器控件"},
    {"RT + Left Stick: Camera left/right/forward/back", "RT + 左搖杆：相機 左/右/前進/後退"},
    {"RT + Right Stick: Camera up/down", "RT + 右搖杆：相機 上/下"},
    {"Page: %d", "頁: %d"},
    {"DPad Left: Previous page | DPad Right: Next page", "左DPad：上壹頁 | 右DPad：下壹頁"},
    {"RT + B: Save Camera 2", "RT + B：保存相機2"},
    {"RT + Y: Save Camera 1", "RT + Y：保存相機1"},
    {"RT + X: Save Camera 0", "RT + X：保存相機0"},
    {"RT + B: Load Camera 2", "RT + B：加載相機2"},
    {"RT + Y: Load Camera 1", "RT + Y：加載相機1"},
    {"RT + X: Load Camera 0", "RT + X：加載相機0"},
    {"RT + B: Reset camera offset", "RT + B：重置相機偏移"},
    {"RT + Y: Recenter view", "RT + Y：重置中心視圖"},
    {"RT + X: Reset standing origin", "RT + X：重置站立原點"},
    {"Uncap Framerate", "取消幀率上限"},
    {"Enable GUI", "開啓視圖"},
    {"Enable Depth", "開啓深度"},
    {"Load Blueprint Code", "加載藍圖代碼"},
    {"Ghosting Fix", "修複鬼影"},
    {"Near Clip Plane", "近裁剪面"},
    {"Enable", "開啓"},
    {"Value", "值"},
    {"Controller", "控制器"},
    {"VR Joystick Deadzone", "VR 搖杆死區"},
    {"DPad Shifting", "DPad 移位"},
    {"DPad Shifting Method", "DPad 移位方法"},
    {"Aim Method", "瞄准方法"},
    {"Experimental, may crash", "實驗性的，可能會崩潰"},
    {"Some games may not work with this enabled.", "啓用此功能後，某些遊戲可能無法運行。"},
    {"Type", "類型"},
    {"Speed", "速度"},
    {"Smoothing", "平滑"},
    {"Modify Player Control Rotation", "修改玩家轉向控制"},
    {"Use Pawn Control Rotation", "使用Pawn控制旋轉"},
    {"Multiplayer Support", "多人遊戲支持"},
    {"Snap Turn", "急轉"},
    {"Enabled", "已啓用"},
    {"Set Snap Turn Rotation Angle in Degrees.", "以度爲單位設置捕捉旋轉旋轉角度。"},
    {"Angle", "角度"},
    {"Set Snap Turn Joystick Deadzone.", "設置快速轉動搖杆死區。"},
    {"Deadzone", "死區"},
    {"Movement Orientation", "運動方向"},
    {"Roomscale Movement", "室內運動"},
    {"Save Camera 0", "保存相機0"},
    {"Save Camera 1", "保存相機1"},
    {"Save Camera 2", "保存相機2"},
    {"Load Camera 0", "加載相機0"},
    {"Load Camera 1", "加載相機1"},
    {"Load Camera 2", "加載相機2"},
    {"Decoupled Pitch", "場地解藕"},
    {"Auto Adjust UI", "自動調整UI"},
    {"Playspace Keys", "遊戲空間按鍵"},
    {"Recenter View Key", "重新居中視圖鍵"},
    {"Set Standing Origin Key", "重置視圖鍵"},
    {"Camera Keys", "相機按鍵"},
    {"Load Camera 0 Key", "加載相機0按鍵"},
    {"Load Camera 1 Key", "加載相機1按鍵"},
    {"Load Camera 2 Key", "加載相機2按鍵"},
    {"Overlay/Runtime Keys", "疊加/運行時按鍵"},
    {"Toggle 2D Screen Mode Key", "切換2D屏幕模式鍵"},
    {"Disable VR Key", "禁用VR鍵"},
    {"Compatibility Options", "兼容性選項"},
    {"Skip UObjectArray Init", "跳過UObjectArray初始化"},
    {"Skip PostInitProperties", "跳過PostInitProperties"},
    {"SceneView Compatibility Mode", "場景視圖兼容模式"},
    {"Extreme Compatibility Mode", "極端兼容模式"},
    {"Splitscreen Compatibility", "分屏兼容性"},
    {"Index", "序號"},
    {"Sync Mode", "同步模式"},
    {"Early\0Late\0Very Late\0", "早\0晚\0非常晚\0"},
    {"Right Bounds", "右側邊界"},
    {"Left Bounds", "左側邊界"},
    {"Disable Projection Matrix Override", "禁用投影矩陣覆蓋"},
    {"Disable View Matrix Override", "禁用視圖矩陣覆蓋"},
    {"Disable Backbuffer Size Override", "禁用備份緩沖區大小覆蓋"},
    {"Disable VR Overlay", "禁用VR覆蓋"},
    {"Disable VR Entirely", "完全禁用VR"},
    {"Stereo Emulation Mode", "立體聲仿真模式"},
    {"Wait for Present", "等待呈現"},
    {"Controllers allowed", "允許的控制器"},
    {"Controller test mode", "控制器測試模式"},
    {"Prediction Scale", "預測標尺"},
    {"Raw Left", "左"},
    {"Raw Right", "右"},
    {"Left Stick", "左搖杆"},
    {"Right Stick", "右搖杆"},
    {"Hardware scheduling: %s", "硬件調度: %s"},
    {"Disabled", "已禁用"},
    {"Loading...", "加載中..."},
    {"%s not loaded: %s not found", "%s未被加載: 未找到%s"},
    {"Please select %s from the loader if you want to use %s", "請從加載器中選擇%s，如果妳想使用%s的話"},
    {"%s not loaded: %s", "%s未被加載: %s"},
    {"%s not loaded: Unknown error", "%s未被加載: 未知錯誤"},
    {"No runtime loaded.", "未加載任何運行時。"},
    {"Attempt to reinitialize", "嘗試重新初始化"},
    {"Set Standing Height", "設置站立高度"},
    {"Set Standing Origin", "設置站立原點"},
    {"Recenter View", "重新居中視圖"},
    {"Reinitialize Runtime", "重新初始化運行時"},
    {"Console/CVars", "控制台/CVars"},
    {"Compatibility", "兼容性"},
    {"Debug", "調試"},
    {"Note: Any changes here will be frozen.", "注意：此處的任何更改都將被凍結。"},
    {"Frozen CVars: %i", "凍結的CVars: %i"},
    {"Display Console", "顯示控制台"},
    {"Spawn Native Console", "生成本地控制台"},
    {"Dump All CVars", "轉儲所有CVars"},
    {"Clear Frozen CVars", "清除凍結的CVars"},
    {"Failed to get FConsoleManager.", "無法獲取FConsoleManager。"},
    {"Note: This is a homebrew console. It is not the same as the in-game console.", "注意: 這是壹個自制的控制台，與遊戲中的控制台不同。"},
    {"Command", "命令"},
    {"Description", "描述"},
    {"Failed to find cvar: %s", "未能找到cvar：%s"},
    {"Unimplemented cvar type: %s", "未實現的cvar類型：%s"},
    {"Failed to read cvar: %s", "讀取cvar失敗: %s"},
    {"Failed to find cvar data: %s", "查找cvar數據失敗: %s"},
    {"Failed to read cvar data: %s", "讀取cvar數據失敗: %s"},
    {"Stereo Hook Options", "立體鈎子選項"},
    {"Asynchronous Code Scanning", "異步代碼掃描"},
    {"Recreate Textures on Reset", "重置時重新創建紋理"},
    {"Frame Delay Compensation", "幀延遲補償"},
    {"Config", "配置"},
    {"Developer", "開發者"},
    {"PluginLoader", "插件加載器"},
    {"Waiting for UObjectBase to be hooked...", "等待UObjectBase被挂鈎..."},
    {"Reload Persistent States", "重新加載持久狀態"},
    {"Destroy Persistent States", "清除持久狀態"},
    {"Enabled at Startup", "在啓動時啓用"},
    {"Enable Attach Lerp", "啓用附加Lerp"},
    {"Dump SDK", "轉儲SDK"},
    {"Attached Components", "附加組件"},
    {"Detach all", "全部分離"},
    {"Attached Camera Object", "附加相機對象"},
    {"Detach Camera", "分離相機"},
    {"Spawn Overlapper", "生成疊加器"},
    {"Overlapped Objects", "疊加的對象"},
    {"Destroy Overlapper", "清除疊加器"},
    {"Attach all", "附加全部"},
    {"Objects: %zu (%zu actual)", "對象: %zu (真實 %zu)"},
    {"Recent Objects", "最近使用的對象"},
    {"Common Objects", "公共對象"},
    {"PlayerController", "玩家控制器"},
    {"Player Controller", "玩家控制器"},
    {"No player controller", "無玩家控制器"},
    {"Acknowledged Pawn", "已確認生成"},
    {"No pawn", "未生成"},
    {"Camera Manager", "相機管理器"},
    {"No camera manager", "無相機管理器"},
    {"World", "世界"},
    {"No world", "無世界"},
    {"Objects by class", "按類排列對象"},
    {"Filter", "過濾"},
    {"Add Component Permanently", "永久添加組件"},
    {"Copy Name", "複制名稱"},
    {"Copy Address", "複制地址"},
    {"Set to Screen Space", "設置爲屏幕空間"},
    {"Detach", "分離"},
    {"Adjust", "調整"},
    {"Permanent Change", "永久變更"},
    {"Save state", "保存狀態"},
    {"Can't save, did not start from a valid base or none of the allowed bases can reach this component", "無法保存，沒有從有效的基類開始的，或者允許的基類不能達到此組件"},
    {"Attach left", "附加左側"},
    {"Attach right", "附加右側"},
    {"Attach Camera to", "附加相機到"},
    {"Attach Camera to (Relative)", "附加相機到(相對的)"},
    {"Camera Offset", "相機偏移"},
    {"Visible", "顯示"},
    {"Save Visibility State", "保存隱藏顯示狀態"},
    {"Apply to all actors", "適用于所有參與者"},
    {"Add Component", "添加組件"},
    {"Components", "組件"},
    {"Call", "調用"},
    {"Disable", "關閉"},
    {"Can't save, did not start from a valid base", "無法保存，沒有從有效的基類開始"},
    {"Empty array", "空數組"},
    {"Failed to get inner property", "無法獲取內部屬性"},
    {"Failed to get inner property class", "無法獲取內部屬性類"},
    {"Array of %s (unsupported)", "%s數組(不支持)"},
    {"Inheritance", "繼承"},
    {"Functions", "方法"},
    {"Properties", "屬性"},
    {"UObjectHook is disabled", "UObjectHook已禁用"},
    {"Re-enable", "重新啓用"},
    {"RotationOffset", "旋轉偏移"},
    {"PositionOffset", "位置偏移"},
    {"L3 + R3 Long Press Menu Toggle", "L3 + R3 長按菜單切換"},
    {"Debug Stats", "調試信息"},
    {"Select GUI Language", "選擇界面語言"},
    {"Runtime Information (NONE)", "運行時信息 (無)"},
    {"Log Level", "日誌等級"},
    {"Enable Depth-based Latency Reduction", "啟用基於深度降低延遲"},
    {"Controller Pitch Offset", "控製器間距偏移"},
    {"Left-handed Controller Inputs", "左控製器輸入"},
    {"Freeze Position", "凍結位置"},
    {"Freeze Rotation", "凍結旋轉"},
    {"Recenter Horizon Key", "重置地面中心快捷鍵"},
    {"Toggle In-Game UI Key", "切換遊戲界面快捷鍵"},
    {"AHUD UI Compatibility", "AHUD UI兼容性"},
    {"Vertical Projection", "垂直投影"},
    {"Horizontal Projection", "水平投影"},
    {"Scale Render Target", "縮放渲染目標"},
    {"Show FPS", "顯示幀率"},
    {"Show Engine Statistics", "顯示引擎統計信息"},
    {"Attach Lerp Speed", "附加Lerp速度"},
    {"UObjectHook Keybinds", "UObjectHook按鍵綁定"},
    {"Disable UObjectHook Key", "禁用UObjectHook快捷鍵"},
    {"Constructor calls: %llu", "構造函數調用: %llu"},
    {"Destructor calls: %llu", "析構函數調用: %llu"},
    {"Native Stereo", "原生立體"},
    {"Synchronized Sequential", "同步序列"},
    {"Alternating/AFR", "交替幀渲染/AFR"},
    {"Skip Tick", "跳過下一刻"},
    {"Skip Draw", "跳過繪製"},
    {"Game", "遊戲"},
    {"Head/HMD", "頭部/頭顯"},
    {"Right Controller", "右控製器"},
    {"Left Controller", "左控製器"},
    {"Two Handed (Right)", "雙手 (右)"},
    {"Two Handed (Left)", "雙手 (左)"},
    {"Left Joystick (Disables Standard Joystick Input)", "Left Joystick (禁用標準搖桿輸入)"},
    {"Right Joystick (Disables Standard Joystick Input)", "Right Joystick (禁用標準搖桿輸入)"},
    {"Gesture (Head) + Left Joystick", "手勢 (頭部) + 左搖桿"},
    {"Gesture (Head) + Right Joystick", "手勢 (頭部) + 右搖桿"},
    {"Raw / default", "原始 / 默認"},
    {"Symmetrical", "對稱"},
    {"Mirrored", "鏡像"},
    {"Matched", "匹配"},
    {"Default Dark", "默認暗色"},
    {"Alternative Dark", "另類暗色"},
    {"Default Light", "默認明亮"},
    {"High Contrast", "高對比度"},
    {"Early", "早"},
    {"Late", "晚"},
    {"Very Late", "非常晚"},
}};

constexpr Entry kSupplementalSimplifiedChinese[]{
    {"Reset to default", "恢复默认"},
    {"Unknown", "未知"},
    {"CVars", "CVars"},
    {"Native Stereo Fix", "原生立体修复"},
    {"Use Same Stereo Pass", "使用同一立体通道"},
    {"Roomscale Movement", "房间尺度移动"},
    {"Sweep Movement", "扫掠移动"},
    {"When enabled, headset movement will affect the movement of the player character.", "启用后，头显移动会影响玩家角色移动。"},
    {"When enabled, roomscale movement will use a sweep to prevent the player from moving through walls.\nThis also allows physics objects to interact with the player, like doors.", "启用后，房间尺度移动会使用扫掠检测，防止玩家穿墙。\n这也允许门等物理对象与玩家交互。"},
    {"Camera Freeze", "相机冻结"},
    {"Camera Lerp", "相机插值"},
    {"Lerp Pitch", "插值俯仰"},
    {"Lerp Yaw", "插值偏航"},
    {"Lerp Roll", "插值滚转"},
    {"Recenter Horizon", "重置水平线"},
    {"Run script", "运行脚本"},
    {"Reset scripts", "重置脚本"},
    {"Spawn Debug Console", "生成调试控制台"},
    {"Garbage Collection Stats", "垃圾回收统计"},
    {"Garbage Collection Handler", "垃圾回收处理器"},
    {"Garbage Collection Mode", "垃圾回收模式"},
    {"Minor GC Multiplier", "次要 GC 倍率"},
    {"Major GC Multiplier", "主要 GC 倍率"},
    {"Garbage Collection Type", "垃圾回收类型"},
    {"Garbage Collection Budget", "垃圾回收预算"},
    {"Log Lua Errors to Disk", "将 Lua 错误写入磁盘"},
    {"Last Error Time: %.2f seconds ago", "上次错误时间：%.2f 秒前"},
    {"Last Script Error: %s", "上次脚本错误：%s"},
    {"No Script Errors... yet!", "目前没有脚本错误。"},
    {"Known scripts:", "已知脚本："},
    {"Megabytes in use: %.2f", "已用内存：%.2f MB"},
    {"Action", "操作"},
    {"Add Binding", "添加绑定"},
    {"Add Vector2 Association", "添加 Vector2 关联"},
    {"Address Lookup", "地址查找"},
    {"All Called Functions", "所有已调用函数"},
    {"Attach HMD", "附加到头显"},
    {"Bindings", "绑定"},
    {"Branch: %s", "分支：%s"},
    {"Build date: %s", "构建日期：%s"},
    {"Build time: %s", "构建时间：%s"},
    {"Call Original", "调用原始函数"},
    {"Called functions: %llu", "已调用函数：%llu"},
    {"Can't save, did not start from a valid base or none of the allowed bases can reach this object", "无法保存，未从有效基准开始，或允许的基准无法到达此对象"},
    {"Cannot determine struct size", "无法确定结构体大小"},
    {"Cannot determine struct type", "无法确定结构体类型"},
    {"Clear Called Functions", "清除已调用函数"},
    {"Clear Ignored Functions", "清除已忽略函数"},
    {"Commit hash: %s", "提交哈希：%s"},
    {"Commits past tag: %i", "标签后提交数：%i"},
    {"Commits: %i", "提交数：%i"},
    {"Create ProcessEvent hook", "创建 ProcessEvent 钩子"},
    {"Create texture", "创建纹理"},
    {"Default Object", "默认对象"},
    {"Destroy Component", "销毁组件"},
    {"Destroy scene capture", "销毁场景捕获"},
    {"Destroy texture", "销毁纹理"},
    {"Failed to display element %d", "显示元素 %d 失败"},
    {"Failed to hook ProcessEvent!", "挂钩 ProcessEvent 失败！"},
    {"Framework error: %s", "框架错误：%s"},
    {"Framework is currently initializing...", "框架正在初始化..."},
    {"Hide Default Classes", "隐藏默认类"},
    {"Ignore", "忽略"},
    {"Ignore All Called Functions", "忽略所有已调用函数"},
    {"Ignore Virtual Desktop Checks", "忽略 Virtual Desktop 检查"},
    {"Insert New Output", "插入新输出"},
    {"Interaction Profile: %s", "交互配置文件：%s"},
    {"Interaction profile not loaded, try putting on your headset.", "交互配置文件尚未加载，请戴上头显重试。"},
    {"Invalid class", "无效类"},
    {"Invalid object", "无效对象"},
    {"Legacy", "旧版"},
    {"Lerp Speed", "插值速度"},
    {"Location", "位置"},
    {"Max Calls", "最大调用次数"},
    {"New Binding (e.g. /user/hand/left/input/trigger)", "新绑定（例如 /user/hand/left/input/trigger）"},
    {"New Vector2 Activator", "新 Vector2 激活项"},
    {"New Vector2 Modifier", "新 Vector2 修饰项"},
    {"New Vector2 Output", "新 Vector2 输出"},
    {"New Vector2 Value", "新 Vector2 值"},
    {"No scripts loaded.", "未加载脚本。"},
    {"Null default object", "空默认对象"},
    {"OpenXR Options", "OpenXR 选项"},
    {"Outer", "外层"},
    {"ProcessEvent Listener", "ProcessEvent 监听器"},
    {"Recent Functions", "最近函数"},
    {"Redirect", "重定向"},
    {"Resolution Scale", "分辨率比例"},
    {"Restore Default Bindings", "恢复默认绑定"},
    {"Rotation", "旋转"},
    {"Save Bindings", "保存绑定"},
    {"Save Property", "保存属性"},
    {"Scene Capture Texture: %s", "场景捕获纹理：%s"},
    {"Script UI", "脚本 UI"},
    {"Search", "搜索"},
    {"Sockets", "插槽"},
    {"Spawn scene capture", "生成场景捕获"},
    {"Tag: %s", "标签：%s"},
    {"This menu will close after initialization if you have the remember option enabled.", "如果启用了记住菜单状态选项，初始化后此菜单会关闭。"},
    {"UI Invert Alpha", "UI 反转 Alpha"},
    {"Unreal Engine VR", "虚幻引擎 VR"},
    {"Unsave Property", "取消保存属性"},
    {"Use FMalloc for ISceneViewExtensions", "为 ISceneViewExtensions 使用 FMalloc"},
    {"Vector2 Associations", "Vector2 关联"},
    {"Virtual Desktop Fix", "Virtual Desktop 修复"},
    {"WARNING: DLSS Frame Generation has been detected. Make sure it is disabled within in-game settings.", "警告：检测到 DLSS 帧生成。请确保在游戏设置中禁用它。"},
    {"X", "X"},
    {"[Called]", "[已调用]"},
    {"[Calling Original]", "[正在调用原始函数]"},
    {"[Default]", "[默认]"},
    {"[Out]", "[输出]"},
    {"[Redirected]", "[已重定向]"},
    {"[empty string]", "[空字符串]"},
    {"null class", "空类"},
    {"nullptr", "空指针"},
};

constexpr Entry kSupplementalTraditionalChinese[]{
    {"Reset to default", "恢復默認"},
    {"Unknown", "未知"},
    {"CVars", "CVars"},
    {"Native Stereo Fix", "原生立體修復"},
    {"Use Same Stereo Pass", "使用同一立體通道"},
    {"Roomscale Movement", "房間尺度移動"},
    {"Sweep Movement", "掃掠移動"},
    {"When enabled, headset movement will affect the movement of the player character.", "啟用後，頭顯移動會影響玩家角色移動。"},
    {"When enabled, roomscale movement will use a sweep to prevent the player from moving through walls.\nThis also allows physics objects to interact with the player, like doors.", "啟用後，房間尺度移動會使用掃掠檢測，防止玩家穿牆。\n這也允許門等物理對象與玩家交互。"},
    {"Camera Freeze", "相機凍結"},
    {"Camera Lerp", "相機插值"},
    {"Lerp Pitch", "插值俯仰"},
    {"Lerp Yaw", "插值偏航"},
    {"Lerp Roll", "插值滾轉"},
    {"Recenter Horizon", "重置水平線"},
    {"Run script", "運行腳本"},
    {"Reset scripts", "重置腳本"},
    {"Spawn Debug Console", "生成調試控制台"},
    {"Garbage Collection Stats", "垃圾回收統計"},
    {"Garbage Collection Handler", "垃圾回收處理器"},
    {"Garbage Collection Mode", "垃圾回收模式"},
    {"Minor GC Multiplier", "次要 GC 倍率"},
    {"Major GC Multiplier", "主要 GC 倍率"},
    {"Garbage Collection Type", "垃圾回收類型"},
    {"Garbage Collection Budget", "垃圾回收預算"},
    {"Log Lua Errors to Disk", "將 Lua 錯誤寫入磁盤"},
    {"Last Error Time: %.2f seconds ago", "上次錯誤時間：%.2f 秒前"},
    {"Last Script Error: %s", "上次腳本錯誤：%s"},
    {"No Script Errors... yet!", "目前沒有腳本錯誤。"},
    {"Known scripts:", "已知腳本："},
    {"Megabytes in use: %.2f", "已用內存：%.2f MB"},
    {"Action", "操作"},
    {"Add Binding", "新增綁定"},
    {"Add Vector2 Association", "新增 Vector2 關聯"},
    {"Address Lookup", "地址查找"},
    {"All Called Functions", "所有已調用函數"},
    {"Attach HMD", "附加到頭顯"},
    {"Bindings", "綁定"},
    {"Branch: %s", "分支：%s"},
    {"Build date: %s", "構建日期：%s"},
    {"Build time: %s", "構建時間：%s"},
    {"Call Original", "調用原始函數"},
    {"Called functions: %llu", "已調用函數：%llu"},
    {"Can't save, did not start from a valid base or none of the allowed bases can reach this object", "無法保存，未從有效基準開始，或允許的基準無法到達此對象"},
    {"Cannot determine struct size", "無法確定結構體大小"},
    {"Cannot determine struct type", "無法確定結構體類型"},
    {"Clear Called Functions", "清除已調用函數"},
    {"Clear Ignored Functions", "清除已忽略函數"},
    {"Commit hash: %s", "提交哈希：%s"},
    {"Commits past tag: %i", "標籤後提交數：%i"},
    {"Commits: %i", "提交數：%i"},
    {"Create ProcessEvent hook", "創建 ProcessEvent 鈎子"},
    {"Create texture", "創建紋理"},
    {"Default Object", "默認對象"},
    {"Destroy Component", "銷毀組件"},
    {"Destroy scene capture", "銷毀場景捕獲"},
    {"Destroy texture", "銷毀紋理"},
    {"Failed to display element %d", "顯示元素 %d 失敗"},
    {"Failed to hook ProcessEvent!", "挂鈎 ProcessEvent 失敗！"},
    {"Framework error: %s", "框架錯誤：%s"},
    {"Framework is currently initializing...", "框架正在初始化..."},
    {"Hide Default Classes", "隱藏默認類"},
    {"Ignore", "忽略"},
    {"Ignore All Called Functions", "忽略所有已調用函數"},
    {"Ignore Virtual Desktop Checks", "忽略 Virtual Desktop 檢查"},
    {"Insert New Output", "插入新輸出"},
    {"Interaction Profile: %s", "交互配置文件：%s"},
    {"Interaction profile not loaded, try putting on your headset.", "交互配置文件尚未加載，請戴上頭顯重試。"},
    {"Invalid class", "無效類"},
    {"Invalid object", "無效對象"},
    {"Legacy", "舊版"},
    {"Lerp Speed", "插值速度"},
    {"Location", "位置"},
    {"Max Calls", "最大調用次數"},
    {"New Binding (e.g. /user/hand/left/input/trigger)", "新綁定（例如 /user/hand/left/input/trigger）"},
    {"New Vector2 Activator", "新 Vector2 激活項"},
    {"New Vector2 Modifier", "新 Vector2 修飾項"},
    {"New Vector2 Output", "新 Vector2 輸出"},
    {"New Vector2 Value", "新 Vector2 值"},
    {"No scripts loaded.", "未加載腳本。"},
    {"Null default object", "空默認對象"},
    {"OpenXR Options", "OpenXR 選項"},
    {"Outer", "外層"},
    {"ProcessEvent Listener", "ProcessEvent 監聽器"},
    {"Recent Functions", "最近函數"},
    {"Redirect", "重定向"},
    {"Resolution Scale", "分辨率比例"},
    {"Restore Default Bindings", "恢復默認綁定"},
    {"Rotation", "旋轉"},
    {"Save Bindings", "保存綁定"},
    {"Save Property", "保存屬性"},
    {"Scene Capture Texture: %s", "場景捕獲紋理：%s"},
    {"Script UI", "腳本 UI"},
    {"Search", "搜索"},
    {"Sockets", "插槽"},
    {"Spawn scene capture", "生成場景捕獲"},
    {"Tag: %s", "標籤：%s"},
    {"This menu will close after initialization if you have the remember option enabled.", "如果啟用了記住菜單狀態選項，初始化後此菜單會關閉。"},
    {"UI Invert Alpha", "UI 反轉 Alpha"},
    {"Unreal Engine VR", "虛幻引擎 VR"},
    {"Unsave Property", "取消保存屬性"},
    {"Use FMalloc for ISceneViewExtensions", "為 ISceneViewExtensions 使用 FMalloc"},
    {"Vector2 Associations", "Vector2 關聯"},
    {"Virtual Desktop Fix", "Virtual Desktop 修復"},
    {"WARNING: DLSS Frame Generation has been detected. Make sure it is disabled within in-game settings.", "警告：檢測到 DLSS 幀生成。請確保在遊戲設置中禁用它。"},
    {"X", "X"},
    {"[Called]", "[已調用]"},
    {"[Calling Original]", "[正在調用原始函數]"},
    {"[Default]", "[默認]"},
    {"[Out]", "[輸出]"},
    {"[Redirected]", "[已重定向]"},
    {"[empty string]", "[空字符串]"},
    {"null class", "空類"},
    {"nullptr", "空指針"},
};

Language s_language{Language::SimplifiedChinese};

const char* lookup(std::string_view text, const auto& entries) {
    for (const auto& entry : entries) {
        if (text == entry.key) {
            return entry.value;
        }
    }

    return nullptr;
}

} // namespace

const std::vector<std::string>& language_options() {
    static const std::vector<std::string> options{
        "English",
        "简体中文-translated by 佐木了",
        "繁體中文-translated by 佐木了",
    };

    return options;
}

Language language() {
    return s_language;
}

void set_language(Language language) {
    s_language = language;
}

const char* tr(const char* text) {
    if (text == nullptr) {
        return "";
    }

    return tr(std::string_view{text});
}

const char* tr(std::string_view text) {
    if (s_language == Language::English || text.empty()) {
        return text.data();
    }

    const char* translated = nullptr;

    switch (s_language) {
    case Language::SimplifiedChinese:
        translated = lookup(text, kSupplementalSimplifiedChinese);
        if (translated == nullptr) {
            translated = lookup(text, kSimplifiedChinese);
        }
        break;
    case Language::TraditionalChinese:
        translated = lookup(text, kSupplementalTraditionalChinese);
        if (translated == nullptr) {
            translated = lookup(text, kTraditionalChinese);
        }
        break;
    default:
        break;
    }

    return translated != nullptr ? translated : text.data();
}

} // namespace Localization
